# Generated by Django 2.2.28 on 2024-12-12 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 13, 2, 59, 31, 256896), verbose_name='Опубликована'),
        ),
        migrations.AlterModelTable(
            name='blog',
            table=None,
        ),
    ]
