# Generated by Django 2.2.28 on 2024-12-13 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20241213_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 12, 13, 3, 4, 45, 726746), verbose_name='Опубликована'),
        ),
    ]
